### ISSUE TITLE
Replacing any sound effect mutes background music

### ISSUE THREAD

**Issue by chendeni** [XAYRGA/wsystool#4]
When replacing any sound effect and running rebuild_baa.bat, all background music from AST files in the stream files are no longer played.  Even replacing a sound effect with itself and not replacing any sound effects and running rebuild_baa.bat causes background music to mute.

**Comment by XAYRGA** [comment]
Hi there, this can be dependent on the platform / other factors too.

If you replace a sound with one that is too long / large, the console can run out of ARAM and it will not load that bank.

Particularly, if you're having problems with streamed files, it's probably not WSYSTool's fault. The more likely culprit is JAMPacked , another tool in the overall group of tools you're using. That tool is currently under a rewrite, so it could be some time before this is appropriately fixed. It could also be corruption of the soundtable caused by the "bast" tool.

I currently don't have a repo for the JAudio Sound Modding Toolkit, so it might be some time before I can properly address this concern, but still wouldn't apply to this individual component.
